version: '3.7'

services:

  sending-api:
    image: "sending-setup"
    ports:
      - "8080:5000"
    networks:
      - my-local-network
    depends_on:
      - sending-db

  receiving-api:
    image: "receiving-setup"
    ports:
      - "8081:5001"
    networks:
      - my-local-network
    restart: on_failure

  sending-db:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=sk,1234Sql
      - MSSQL_PID=Express
      - ACCEPT_EULA=Y
    networks:
      - my-local-network

networks:
  my-local-network:
